/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;
import java.nio.file.Path;

public class App {
  public static void main(String[] args) {
    if (args.length != 3) {
      System.out.println("Try again!: App <input-file-path> <output-file-path> <transform-name>");
      return;
    }

    String inputFilePath = args[0];
    String outputFilePath = args[1];
    String transformName = args[2];

    try {
      Bitmap bitmap = new Bitmap(Path.of(inputFilePath));

      // types of transforms to choose using a switch case, there's got to be an easier way.
      switch (transformName) {
        case "invert":
          bitmap.invertColors();
          break;
        case "grayscale":
          bitmap.grayscaleColors();
          break;
        case "sepia":
          bitmap.sepiaFilter();
          break;
        default:
          System.out.println("Ain't nobody got time for that: " + transformName);
          return;
      }

      // instead of return it do a file
      bitmap.writeToFile(Path.of(outputFilePath));

      System.out.println("Image has been BAKED... HAHA YEAH BRO!");
    } catch (IOException e) {
      System.out.println("An error occurred while your image was getting baked: " + e.getMessage());
    } catch (IllegalArgumentException e) {
      System.out.println(e.getMessage());
    }
  }
}
